services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - dash
      - shared_net
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - dash
    volumes:
      - postgres-data:/var/lib/postgresql/data

  maestral:
    image: maestraldbx/maestral
    volumes:
      - maestral_data:/dropbox

networks:
  dash:
  shared_net:
    external: true

volumes:
  postgres-data:
  maestral_data:
