import { pgTable, pgSchema, text, varchar, numeric, integer, date, bigint, doublePrecision, boolean, timestamp, json } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

export const analyticsMart = pgSchema("analytics_mart");


export const martAccountAttentionQueueInAnalyticsMart = analyticsMart.table("mart_account_attention_queue", {
	companyDomainKey: text("company_domain_key"),
	companyName: varchar("company_name"),
	businessSizeCategory: text("business_size_category"),
	revenueCategory: text("revenue_category"),
	healthScore: numeric("health_score"),
	healthCategory: text("health_category"),
	activityStatus: text("activity_status"),
	engagementLevel: text("engagement_level"),
	combinedGrowthTrend: text("combined_growth_trend"),
	growthTrendDirection: text("growth_trend_direction"),
	daysSinceLastOrder: integer("days_since_last_order"),
	lastOrderDate: date("last_order_date"),
	firstOrderDate: date("first_order_date"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	totalOrders: bigint("total_orders", { mode: "number" }),
	totalRevenue: numeric("total_revenue"),
	avgOrderValue: numeric("avg_order_value"),
	trailing90DRevenue: numeric("trailing_90d_revenue"),
	trailing1YRevenue: numeric("trailing_1y_revenue"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	ordersLast90Days: bigint("orders_last_90_days", { mode: "number" }),
	revenueLast90Days: numeric("revenue_last_90_days"),
	revenuePercentile: doublePrecision("revenue_percentile"),
	hasEstablishedPurchasePattern: boolean("has_established_purchase_pattern"),
	isMeaningfulRevenueAccount: boolean("is_meaningful_revenue_account"),
	hasCurrentRiskIssue: boolean("has_current_risk_issue"),
	isHighValueAccount: boolean("is_high_value_account"),
	isHighValueAtRisk: boolean("is_high_value_at_risk"),
	isGrowthOpportunity: boolean("is_growth_opportunity"),
	isDormantHighValue: boolean("is_dormant_high_value"),
	isDecliningActive: boolean("is_declining_active"),
	attentionScore: integer("attention_score"),
	reasonCodes: text("reason_codes"),
	bestContactId: text("best_contact_id"),
	bestContactName: text("best_contact_name"),
	bestContactEmail: text("best_contact_email"),
	bestContactPhone: text("best_contact_phone"),
	bestContactRole: text("best_contact_role"),
	bestContactIsBilling: boolean("best_contact_is_billing"),
	bestContactIsGeneric: boolean("best_contact_is_generic"),
	bestContactIsInternal: boolean("best_contact_is_internal"),
	bestContactIsLikelyHuman: boolean("best_contact_is_likely_human"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const martInventoryInboundLinesInAnalyticsMart = analyticsMart.table("mart_inventory_inbound_lines", {
	inboundLineId: text("inbound_line_id"),
	inventoryAsOfDate: date("inventory_as_of_date"),
	sku: varchar(),
	inboundType: text("inbound_type"),
	documentNumber: text("document_number"),
	vendor: text(),
	documentDate: date("document_date"),
	expectedOrReceiptDate: date("expected_or_receipt_date"),
	quantity: numeric(),
	rate: numeric(),
	amount: numeric(),
	status: text(),
	sourceTransactionKey: text("source_transaction_key"),
	quickbooksInternalId: text("quickbooks_internal_id"),
	sourceTransactionId: text("source_transaction_id"),
	inboundNote: text("inbound_note"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const martInventorySkuPolicyInAnalyticsMart = analyticsMart.table("mart_inventory_sku_policy", {
	sku: varchar(),
	inventoryAsOfDate: date("inventory_as_of_date"),
	policyBucket: text("policy_bucket"),
	policyAssignmentReason: text("policy_assignment_reason"),
	policyValidationStatus: text("policy_validation_status"),
	policyReviewFlags: text("policy_review_flags"),
	forecastMethod: text("forecast_method"),
	confidenceLevel: text("confidence_level"),
	requiresManualReview: boolean("requires_manual_review"),
	salesDescription: varchar("sales_description"),
	productFamily: text("product_family"),
	materialType: text("material_type"),
	isKit: boolean("is_kit"),
	itemType: varchar("item_type"),
	itemSubtype: varchar("item_subtype"),
	packagingType: text("packaging_type"),
	unitsPerSku: integer("units_per_sku"),
	unitOfMeasure: varchar("unit_of_measure"),
	currentOnHandQty: numeric("current_on_hand_qty"),
	estimatedAvailableQuantity: numeric("estimated_available_quantity"),
	estimatedTotalVisibility: doublePrecision("estimated_total_visibility"),
	quantityOnOrder: numeric("quantity_on_order"),
	quantityOnSalesOrder: numeric("quantity_on_sales_order"),
	openPoQuantity: doublePrecision("open_po_quantity"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	openPoLineCount: bigint("open_po_line_count", { mode: "number" }),
	nextOpenPoDate: date("next_open_po_date"),
	futureReceiptQtyAfterAnchor: numeric("future_receipt_qty_after_anchor"),
	futureReceiptLineCountAfterAnchor: numeric("future_receipt_line_count_after_anchor"),
	avgDailySales30D: numeric("avg_daily_sales_30d"),
	avgDailySales90D: numeric("avg_daily_sales_90d"),
	avgDailySales365D: numeric("avg_daily_sales_365d"),
	inventoryStatus: text("inventory_status"),
	purchaseCost: numeric("purchase_cost", { precision: 38, scale:  9 }),
	salesPrice: numeric("sales_price", { precision: 38, scale:  9 }),
	inventoryValueAtCost: numeric("inventory_value_at_cost"),
	itemStatus: boolean("item_status"),
	isSuppressedFromInventoryPlanning: boolean("is_suppressed_from_inventory_planning"),
	inventorySuppressionReason: text("inventory_suppression_reason"),
	firstSaleMonth: date("first_sale_month"),
	lastSaleMonth: date("last_sale_month"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	monthsWithSalesAllTime: bigint("months_with_sales_all_time", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	monthsWithSalesSince2023: bigint("months_with_sales_since_2023", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	monthsWithSalesSince2024: bigint("months_with_sales_since_2024", { mode: "number" }),
	totalSalesQtyAllTime: numeric("total_sales_qty_all_time"),
	salesQtySince2024: numeric("sales_qty_since_2024"),
	salesQtySince2025: numeric("sales_qty_since_2025"),
	componentConsumedQtyAllTime: numeric("component_consumed_qty_all_time"),
	componentConsumedQtySince2024: numeric("component_consumed_qty_since_2024"),
	latestComponentConsumptionDate: date("latest_component_consumption_date"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	consumedByAssemblySkuCount: bigint("consumed_by_assembly_sku_count", { mode: "number" }),
	buildProducedQtyAllTime: numeric("build_produced_qty_all_time"),
	buildProducedQtySince2024: numeric("build_produced_qty_since_2024"),
	latestBuildDate: date("latest_build_date"),
	fbaTransferInQtyAllTime: numeric("fba_transfer_in_qty_all_time"),
	fbaTransferInQtySince2024: numeric("fba_transfer_in_qty_since_2024"),
	latestFbaTransferDate: date("latest_fba_transfer_date"),
	largestSalesLineQty2025: numeric("largest_sales_line_qty_2025"),
	totalSalesQty2025: numeric("total_sales_qty_2025"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	salesLineCount2025: bigint("sales_line_count_2025", { mode: "number" }),
	largestSalesLineShare2025: numeric("largest_sales_line_share_2025"),
	componentToSalesQtyRatioSince2024: numeric("component_to_sales_qty_ratio_since_2024"),
	hasLargeOrderOutlier2025: boolean("has_large_order_outlier_2025"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const martInventoryReorderRecommendationsInAnalyticsMart = analyticsMart.table("mart_inventory_reorder_recommendations", {
	sku: varchar(),
	inventoryAsOfDate: date("inventory_as_of_date"),
	policyBucket: text("policy_bucket"),
	policyAssignmentReason: text("policy_assignment_reason"),
	policyValidationStatus: text("policy_validation_status"),
	policyReviewFlags: text("policy_review_flags"),
	forecastMethod: text("forecast_method"),
	forecastModelDetail: text("forecast_model_detail"),
	confidenceLevel: text("confidence_level"),
	requiresManualReview: boolean("requires_manual_review"),
	shouldReorder: boolean("should_reorder"),
	reorderQty: doublePrecision("reorder_qty"),
	sixPackUnitsPerLayer: integer("six_pack_units_per_layer"),
	layerRoundedReorderQty: doublePrecision("layer_rounded_reorder_qty"),
	reorderLayerCount: doublePrecision("reorder_layer_count"),
	layerRoundingExtraQty: doublePrecision("layer_rounding_extra_qty"),
	reorderValueAtCost: doublePrecision("reorder_value_at_cost"),
	reorderByDate: date("reorder_by_date"),
	projectedStockoutOrSafetyDate: date("projected_stockout_or_safety_date"),
	expectedReceiptDate: date("expected_receipt_date"),
	preferredVendor: text("preferred_vendor"),
	assumedLeadTimeDays: integer("assumed_lead_time_days"),
	leadTimeSource: text("lead_time_source"),
	planningOverrideReason: text("planning_override_reason"),
	configuredLeadTimeDays: numeric("configured_lead_time_days"),
	observedSkuVendorLeadTimeDays: doublePrecision("observed_sku_vendor_lead_time_days"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	observedSkuVendorLeadTimeCount: bigint("observed_sku_vendor_lead_time_count", { mode: "number" }),
	observedVendorLeadTimeDays: doublePrecision("observed_vendor_lead_time_days"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	observedVendorLeadTimeCount: bigint("observed_vendor_lead_time_count", { mode: "number" }),
	defaultPolicyLeadTimeDays: integer("default_policy_lead_time_days"),
	targetCoverageDays: integer("target_coverage_days"),
	defaultTargetCoverageDays: integer("default_target_coverage_days"),
	targetCoverageSource: text("target_coverage_source"),
	observedSkuVendorOrderCycleDays: doublePrecision("observed_sku_vendor_order_cycle_days"),
	observedSkuVendorMedianOrderCycleDays: doublePrecision("observed_sku_vendor_median_order_cycle_days"),
	observedSkuVendorOrderCycleCount: bigint("observed_sku_vendor_order_cycle_count", { mode: "number" }),
	currentOnHandQty: numeric("current_on_hand_qty"),
	committedDemandQty: numeric("committed_demand_qty"),
	committedDemandBeforeExpectedReceiptQty: numeric("committed_demand_before_expected_receipt_qty"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	committedOrderCount: bigint("committed_order_count", { mode: "number" }),
	firstCommittedDemandDate: date("first_committed_demand_date"),
	lastCommittedDemandDate: date("last_committed_demand_date"),
	inboundOpenPoQty: doublePrecision("inbound_open_po_qty"),
	inboundQtyByExpectedReceiptDate: doublePrecision("inbound_qty_by_expected_receipt_date"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	openPoLineCount: bigint("open_po_line_count", { mode: "number" }),
	nextOpenPoDate: date("next_open_po_date"),
	futureReceiptQtyAfterAnchor: numeric("future_receipt_qty_after_anchor"),
	futureReceiptLineCountAfterAnchor: numeric("future_receipt_line_count_after_anchor"),
	quickbooksQuantityOnOrder: numeric("quickbooks_quantity_on_order"),
	availablePositionQty: doublePrecision("available_position_qty"),
	forecastDailyQty: doublePrecision("forecast_daily_qty"),
	forecastMonthlyQty: doublePrecision("forecast_monthly_qty"),
	skuBaselineMonthlyQty: doublePrecision("sku_baseline_monthly_qty"),
	appliedSeasonalityIndex: doublePrecision("applied_seasonality_index"),
	appliedGrowthFactor: doublePrecision("applied_growth_factor"),
	forecastLeadTimeQty: doublePrecision("forecast_lead_time_qty"),
	safetyStockQty: doublePrecision("safety_stock_qty"),
	safetyStockSource: text("safety_stock_source"),
	demandVariabilitySource: text("demand_variability_source"),
	policySafetyStockQty: doublePrecision("policy_safety_stock_qty"),
	percentileSafetyStockQty: doublePrecision("percentile_safety_stock_qty"),
	variabilitySampleWindows: bigint("variability_sample_windows", { mode: "number" }),
	variabilityWindowsWithDemand: bigint("variability_windows_with_demand", { mode: "number" }),
	avgHistoricalLeadTimeDemandQty: doublePrecision("avg_historical_lead_time_demand_qty"),
	stddevHistoricalLeadTimeDemandQty: doublePrecision("stddev_historical_lead_time_demand_qty"),
	p50HistoricalLeadTimeDemandQty: doublePrecision("p50_historical_lead_time_demand_qty"),
	p75HistoricalLeadTimeDemandQty: doublePrecision("p75_historical_lead_time_demand_qty"),
	p90HistoricalLeadTimeDemandQty: doublePrecision("p90_historical_lead_time_demand_qty"),
	p95HistoricalLeadTimeDemandQty: doublePrecision("p95_historical_lead_time_demand_qty"),
	reorderPointQty: doublePrecision("reorder_point_qty"),
	projectedPositionAtExpectedReceiptQty: doublePrecision("projected_position_at_expected_receipt_qty"),
	uncoveredLeadTimeDemandQty: doublePrecision("uncovered_lead_time_demand_qty"),
	stockoutGapQty: doublePrecision("stockout_gap_qty"),
	rawReorderQty: doublePrecision("raw_reorder_qty"),
	avgDailySales30D: doublePrecision("avg_daily_sales_30d"),
	avgDailySales90D: doublePrecision("avg_daily_sales_90d"),
	avgDailySales365D: doublePrecision("avg_daily_sales_365d"),
	stddevDailySales90D: doublePrecision("stddev_daily_sales_90d"),
	p80DailySales90D: doublePrecision("p80_daily_sales_90d"),
	totalSalesQty90D: doublePrecision("total_sales_qty_90d"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	daysWithSales90D: bigint("days_with_sales_90d", { mode: "number" }),
	avgMonthlySales36M: doublePrecision("avg_monthly_sales_36m"),
	trailing3MAvgMonthlySales: doublePrecision("trailing_3m_avg_monthly_sales"),
	trailing12MAvgMonthlySales: doublePrecision("trailing_12m_avg_monthly_sales"),
	prior12MAvgMonthlySales: doublePrecision("prior_12m_avg_monthly_sales"),
	cappedSalesQty12M: doublePrecision("capped_sales_qty_12m"),
	uncappedSalesQty12M: numeric("uncapped_sales_qty_12m"),
	cappedReductionQty12M: doublePrecision("capped_reduction_qty_12m"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	monthsWithCappedSales36M: bigint("months_with_capped_sales_36m", { mode: "number" }),
	skuSeasonalityIndex: doublePrecision("sku_seasonality_index"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	skuSeasonalityDemandMonths: bigint("sku_seasonality_demand_months", { mode: "number" }),
	familyMaterialSeasonalityIndex: doublePrecision("family_material_seasonality_index"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	familyMaterialDemandMonths: bigint("family_material_demand_months", { mode: "number" }),
	demandGrowthFactor: doublePrecision("demand_growth_factor"),
	forecastMonthNumber: integer("forecast_month_number"),
	salesQtySince2024: numeric("sales_qty_since_2024"),
	salesQtySince2025: numeric("sales_qty_since_2025"),
	componentConsumedQtySince2024: numeric("component_consumed_qty_since_2024"),
	buildProducedQtySince2024: numeric("build_produced_qty_since_2024"),
	fbaTransferInQtySince2024: numeric("fba_transfer_in_qty_since_2024"),
	largestSalesLineShare2025: numeric("largest_sales_line_share_2025"),
	hasLargeOrderOutlier2025: boolean("has_large_order_outlier_2025"),
	isSuppressedFromInventoryPlanning: boolean("is_suppressed_from_inventory_planning"),
	inventorySuppressionReason: text("inventory_suppression_reason"),
	salesDescription: varchar("sales_description"),
	productFamily: text("product_family"),
	materialType: text("material_type"),
	isKit: boolean("is_kit"),
	itemType: varchar("item_type"),
	itemSubtype: varchar("item_subtype"),
	packagingType: text("packaging_type"),
	unitsPerSku: integer("units_per_sku"),
	unitOfMeasure: varchar("unit_of_measure"),
	purchaseCost: numeric("purchase_cost", { precision: 38, scale:  9 }),
	salesPrice: numeric("sales_price", { precision: 38, scale:  9 }),
	inventoryValueAtCost: numeric("inventory_value_at_cost"),
	inventoryStatus: text("inventory_status"),
	recommendationReason: text("recommendation_reason"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const martProductGrowthQualityInAnalyticsMart = analyticsMart.table("mart_product_growth_quality", {
	sku: varchar(),
	productFamily: text("product_family"),
	materialType: text("material_type"),
	isKit: boolean("is_kit"),
	itemType: varchar("item_type"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	orderCount: bigint("order_count", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	customerCount: bigint("customer_count", { mode: "number" }),
	unitsSold: numeric("units_sold"),
	componentUnitsSold: numeric("component_units_sold"),
	revenue: numeric(),
	grossMarginAmount: numeric("gross_margin_amount"),
	grossMarginPercentage: numeric("gross_margin_percentage"),
	discountLeakageAmount: numeric("discount_leakage_amount"),
	currentYearRevenue: numeric("current_year_revenue"),
	priorYearSamePeriodRevenue: numeric("prior_year_same_period_revenue"),
	yoyRevenueGrowthPct: numeric("yoy_revenue_growth_pct"),
	avgActualUnitPrice: numeric("avg_actual_unit_price"),
	avgStandardSalesPrice: numeric("avg_standard_sales_price"),
	avgPurchaseCost: numeric("avg_purchase_cost"),
	latestOrderDate: date("latest_order_date"),
	inventoryDate: date("inventory_date"),
	estimatedAvailableQuantity: numeric("estimated_available_quantity"),
	inventoryValueAtCost: numeric("inventory_value_at_cost"),
	inventoryStatus: text("inventory_status"),
	preferredVendor: text("preferred_vendor"),
	shouldReorder: boolean("should_reorder"),
	requiresManualReview: boolean("requires_manual_review"),
	reorderValueAtCost: doublePrecision("reorder_value_at_cost"),
	topCustomer: varchar("top_customer"),
	topCustomerRevenue: numeric("top_customer_revenue"),
	topCustomerRevenueSharePct: numeric("top_customer_revenue_share_pct"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	revenueRank: bigint("revenue_rank", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	marginRank: bigint("margin_rank", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	familyRevenueRank: bigint("family_revenue_rank", { mode: "number" }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const martDataQualityFlagsInAnalyticsMart = analyticsMart.table("mart_data_quality_flags", {
	flagKey: text("flag_key"),
	severity: text(),
	flagValue: numeric("flag_value"),
	flagLabel: text("flag_label"),
	details: text(),
	detectedAt: timestamp("detected_at", { withTimezone: true, mode: 'string' }),
});

export const martBusinessCockpitSummaryInAnalyticsMart = analyticsMart.table("mart_business_cockpit_summary", {
	asOfDate: date("as_of_date"),
	ytdRevenue: numeric("ytd_revenue"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	ytdOrders: bigint("ytd_orders", { mode: "number" }),
	priorYtdRevenue: numeric("prior_ytd_revenue"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	priorYtdOrders: bigint("prior_ytd_orders", { mode: "number" }),
	ytdRevenueGrowthPct: numeric("ytd_revenue_growth_pct"),
	ytdOrderGrowthPct: numeric("ytd_order_growth_pct"),
	trailing365DRevenue: numeric("trailing_365d_revenue"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	trailing365DOrders: bigint("trailing_365d_orders", { mode: "number" }),
	priorTrailing365DRevenue: numeric("prior_trailing_365d_revenue"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	priorTrailing365DOrders: bigint("prior_trailing_365d_orders", { mode: "number" }),
	trailing365DRevenueGrowthPct: numeric("trailing_365d_revenue_growth_pct"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	openInvoiceCount: bigint("open_invoice_count", { mode: "number" }),
	openArAmount: numeric("open_ar_amount"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	overdueInvoiceCount: bigint("overdue_invoice_count", { mode: "number" }),
	overdueArAmount: numeric("overdue_ar_amount"),
	inventoryAsOfDate: date("inventory_as_of_date"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	reorderSkuCount: bigint("reorder_sku_count", { mode: "number" }),
	suggestedBuyCost: doublePrecision("suggested_buy_cost"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	manualReviewSkuCount: bigint("manual_review_sku_count", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	futureOrderCount: bigint("future_order_count", { mode: "number" }),
	futureOrderAmount: numeric("future_order_amount"),
	latestFutureOrderDate: date("latest_future_order_date"),
	attributionOrderCoveragePct: numeric("attribution_order_coverage_pct"),
	attributionRevenueCoveragePct: numeric("attribution_revenue_coverage_pct"),
	top10CorporateRevenueSharePct: numeric("top_10_corporate_revenue_share_pct"),
	top50CorporateRevenueSharePct: numeric("top_50_corporate_revenue_share_pct"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const fctCompaniesInAnalyticsMart = analyticsMart.table("fct_companies", {
	companyDomainKey: text("company_domain_key"),
	domainType: text("domain_type"),
	companyName: varchar("company_name"),
	primaryEmail: varchar("primary_email"),
	primaryPhone: varchar("primary_phone"),
	primaryBillingAddressLine1: varchar("primary_billing_address_line_1"),
	primaryBillingCity: varchar("primary_billing_city"),
	primaryBillingState: varchar("primary_billing_state"),
	primaryBillingPostalCode: varchar("primary_billing_postal_code"),
	primaryCountry: text("primary_country"),
	region: text(),
	countryCategory: text("country_category"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	customerCount: bigint("customer_count", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	uniqueCustomerNames: bigint("unique_customer_names", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	uniqueCompanyNames: bigint("unique_company_names", { mode: "number" }),
	totalCurrentBalance: numeric("total_current_balance"),
	totalRevenue: doublePrecision("total_revenue"),
	totalOrders: numeric("total_orders"),
	totalLineItems: numeric("total_line_items"),
	firstOrderDate: date("first_order_date"),
	latestOrderDate: date("latest_order_date"),
	businessSizeCategory: text("business_size_category"),
	revenueCategory: text("revenue_category"),
	customerNamesSample: text("customer_names_sample"),
	hasRevenue: boolean("has_revenue"),
	isMultiLocation: boolean("is_multi_location"),
	isCorporate: boolean("is_corporate"),
	enrichedIndustry: varchar("enriched_industry"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	enrichedEmployeeCount: bigint("enriched_employee_count", { mode: "number" }),
	enrichedDescription: varchar("enriched_description"),
	enrichedFoundedYear: integer("enriched_founded_year"),
	enrichedAnnualRevenue: varchar("enriched_annual_revenue"),
	enrichmentSource: varchar("enrichment_source"),
	enrichmentDate: timestamp("enrichment_date", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const dimCustomerContactsInAnalyticsMart = analyticsMart.table("dim_customer_contacts", {
	contactDimKey: text("contact_dim_key"),
	contactId: text("contact_id"),
	fullName: text("full_name"),
	firstName: text("first_name"),
	lastName: text("last_name"),
	nameTitle: text("name_title"),
	jobTitle: text("job_title"),
	primaryEmail: text("primary_email"),
	secondaryEmail: text("secondary_email"),
	primaryPhone: text("primary_phone"),
	additionalContactMethods: json("additional_contact_methods"),
	primaryContactMethod: text("primary_contact_method"),
	companyDomainKey: text("company_domain_key"),
	companyName: text("company_name"),
	contactRole: text("contact_role"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	companyContactRank: bigint("company_contact_rank", { mode: "number" }),
	isPrimaryCompanyContact: boolean("is_primary_company_contact"),
	companyHasMultipleContacts: boolean("company_has_multiple_contacts"),
	companyCountry: text("company_country"),
	companyRegion: text("company_region"),
	companyTotalRevenue: doublePrecision("company_total_revenue"),
	companyTotalOrders: numeric("company_total_orders"),
	businessSizeCategory: text("business_size_category"),
	revenueCategory: text("revenue_category"),
	hasMainEmail: boolean("has_main_email"),
	hasCcEmail: boolean("has_cc_email"),
	hasFullName: boolean("has_full_name"),
	hasJobTitle: boolean("has_job_title"),
	hasPhone: boolean("has_phone"),
	isIndividualCustomer: boolean("is_individual_customer"),
	domainType: text("domain_type"),
	customerType: varchar("customer_type"),
	primaryAddress: varchar("primary_address"),
	city: varchar(),
	state: varchar(),
	postalCode: varchar("postal_code"),
	currentBalance: numeric("current_balance", { precision: 38, scale:  9 }),
	customerStatus: varchar("customer_status"),
	contactDataQuality: text("contact_data_quality"),
	contactTier: text("contact_tier"),
	emailMarketable: boolean("email_marketable"),
	phoneContactable: boolean("phone_contactable"),
	keyAccountContact: boolean("key_account_contact"),
	sourceCustomerId: varchar("source_customer_id"),
	sourceCustomerName: varchar("source_customer_name"),
	sourceCompanyName: varchar("source_company_name"),
	customerCreatedDate: varchar("customer_created_date"),
	customerModifiedDate: varchar("customer_modified_date"),
	isSeed: boolean("is_seed"),
	loadDate: varchar("load_date"),
	contactProcessedAt: timestamp("contact_processed_at", { withTimezone: true, mode: 'string' }),
	dimensionCreatedAt: timestamp("dimension_created_at", { withTimezone: true, mode: 'string' }),
});

export const fctInventoryHistoryInAnalyticsMart = analyticsMart.table("fct_inventory_history", {
	sku: varchar(),
	inventoryDate: date("inventory_date"),
	salesQty: numeric("sales_qty"),
	receiptQty: numeric("receipt_qty"),
	adjustmentQty: numeric("adjustment_qty"),
	netInventoryMovement: numeric("net_inventory_movement"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	orderCount: bigint("order_count", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	lineItemCount: bigint("line_item_count", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	receiptLineCount: bigint("receipt_line_count", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	adjustmentLineCount: bigint("adjustment_line_count", { mode: "number" }),
	includesFutureDatedOrders: boolean("includes_future_dated_orders"),
	estimatedBeginningInventory: numeric("estimated_beginning_inventory"),
	estimatedEndingInventory: numeric("estimated_ending_inventory"),
	inventoryChange: numeric("inventory_change"),
	anchorDate: date("anchor_date"),
	quickbooksQuantityOnHand: numeric("quickbooks_quantity_on_hand", { precision: 38, scale:  9 }),
	anchorQuantityOnHand: numeric("anchor_quantity_on_hand"),
	futureReceiptQtyAfterAnchor: numeric("future_receipt_qty_after_anchor"),
	futureReceiptLineCountAfterAnchor: numeric("future_receipt_line_count_after_anchor"),
	isAnchorDay: boolean("is_anchor_day"),
	isProjectedDay: boolean("is_projected_day"),
	daysSinceAnchor: integer("days_since_anchor"),
	inventoryBasis: text("inventory_basis"),
	quantityOnOrder: numeric("quantity_on_order"),
	quantityOnSalesOrder: numeric("quantity_on_sales_order"),
	openPoQuantity: doublePrecision("open_po_quantity"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	openPoLineCount: bigint("open_po_line_count", { mode: "number" }),
	nextOpenPoDate: date("next_open_po_date"),
	hasOpenPoInbound: boolean("has_open_po_inbound"),
	estimatedAvailableQuantity: numeric("estimated_available_quantity"),
	estimatedTotalVisibility: doublePrecision("estimated_total_visibility"),
	avgDailySales30D: numeric("avg_daily_sales_30d"),
	avgDailySales90D: numeric("avg_daily_sales_90d"),
	avgDailySales365D: numeric("avg_daily_sales_365d"),
	daysRemaining90DVelocity: numeric("days_remaining_90d_velocity"),
	estimatedStockoutDate: date("estimated_stockout_date"),
	inventoryStatus: text("inventory_status"),
	salesDescription: varchar("sales_description"),
	productFamily: text("product_family"),
	materialType: text("material_type"),
	isKit: boolean("is_kit"),
	itemType: varchar("item_type"),
	itemSubtype: varchar("item_subtype"),
	packagingType: text("packaging_type"),
	unitsPerSku: integer("units_per_sku"),
	unitOfMeasure: varchar("unit_of_measure"),
	salesPrice: numeric("sales_price", { precision: 38, scale:  9 }),
	purchaseCost: numeric("purchase_cost", { precision: 38, scale:  9 }),
	inventoryValueAtCost: numeric("inventory_value_at_cost"),
	inventoryValueAtSalesPrice: numeric("inventory_value_at_sales_price"),
	itemStatus: boolean("item_status"),
});

export const dimCustomerContactsFixedInAnalyticsMart = analyticsMart.table("dim_customer_contacts_fixed", {
	contactId: text("contact_id"),
	contactDimKey: text("contact_dim_key"),
	fullName: text("full_name"),
	firstName: text("first_name"),
	lastName: text("last_name"),
	nameTitle: text("name_title"),
	jobTitle: text("job_title"),
	primaryEmail: text("primary_email"),
	secondaryEmail: text("secondary_email"),
	primaryPhone: text("primary_phone"),
	additionalContactMethods: json("additional_contact_methods"),
	primaryContactMethod: text("primary_contact_method"),
	companyDomainKey: text("company_domain_key"),
	companyName: text("company_name"),
	contactRole: text("contact_role"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	companyContactRank: bigint("company_contact_rank", { mode: "number" }),
	isPrimaryCompanyContact: boolean("is_primary_company_contact"),
	companyHasMultipleContacts: boolean("company_has_multiple_contacts"),
	companyCountry: text("company_country"),
	companyRegion: text("company_region"),
	companyTotalRevenue: doublePrecision("company_total_revenue"),
	companyTotalOrders: numeric("company_total_orders"),
	businessSizeCategory: text("business_size_category"),
	revenueCategory: text("revenue_category"),
	hasMainEmail: boolean("has_main_email"),
	hasCcEmail: boolean("has_cc_email"),
	hasFullName: boolean("has_full_name"),
	hasJobTitle: boolean("has_job_title"),
	hasPhone: boolean("has_phone"),
	isIndividualCustomer: boolean("is_individual_customer"),
	domainType: text("domain_type"),
	customerType: varchar("customer_type"),
	primaryAddress: text("primary_address"),
	city: text(),
	state: text(),
	postalCode: text("postal_code"),
	currentBalance: numeric("current_balance"),
	customerStatus: varchar("customer_status"),
	completenessScore: integer("completeness_score"),
	contactDataQuality: text("contact_data_quality"),
	contactTier: text("contact_tier"),
	engagementPotential: text("engagement_potential"),
	emailMarketable: boolean("email_marketable"),
	phoneContactable: boolean("phone_contactable"),
	keyAccountContact: boolean("key_account_contact"),
	sourceCustomerId: varchar("source_customer_id"),
	sourceCustomerName: text("source_customer_name"),
	sourceCompanyName: text("source_company_name"),
	customerCreatedDate: date("customer_created_date"),
	customerModifiedDate: date("customer_modified_date"),
	isSeed: boolean("is_seed"),
	loadDate: varchar("load_date"),
	contactProcessedAt: timestamp("contact_processed_at", { withTimezone: true, mode: 'string' }),
	dimensionCreatedAt: timestamp("dimension_created_at", { withTimezone: true, mode: 'string' }),
});

export const fctOrdersInAnalyticsMart = analyticsMart.table("fct_orders", {
	orderKey: text("order_key"),
	orderNumber: text("order_number"),
	sourceType: text("source_type"),
	orderDate: date("order_date"),
	customer: text(),
	paymentMethod: text("payment_method"),
	status: text(),
	dueDate: date("due_date"),
	primaryContactId: text("primary_contact_id"),
	primaryContactName: text("primary_contact_name"),
	primaryContactEmail: text("primary_contact_email"),
	primaryContactPhone: text("primary_contact_phone"),
	primaryContactRole: text("primary_contact_role"),
	isTaxExempt: boolean("is_tax_exempt"),
	isPaid: boolean("is_paid"),
	isBackdated: boolean("is_backdated"),
	billingAddress: text("billing_address"),
	billingAddressCity: text("billing_address_city"),
	billingAddressState: text("billing_address_state"),
	billingAddressPostalCode: text("billing_address_postal_code"),
	billingAddressCountry: text("billing_address_country"),
	shippingAddress: text("shipping_address"),
	shippingAddressCity: text("shipping_address_city"),
	shippingAddressState: text("shipping_address_state"),
	shippingAddressPostalCode: text("shipping_address_postal_code"),
	shippingAddressCountry: text("shipping_address_country"),
	primaryCountry: text("primary_country"),
	countryCategory: text("country_category"),
	region: text(),
	shippingMethod: text("shipping_method"),
	shipDate: date("ship_date"),
	salesChannelSource: text("sales_channel_source"),
	acquisitionChannel: text("acquisition_channel"),
	utmSource: text("utm_source"),
	utmMedium: text("utm_medium"),
	utmCampaign: text("utm_campaign"),
	landingSite: text("landing_site"),
	referringSite: varchar("referring_site"),
	trackingNumber: text("tracking_number"),
	trackingCompany: text("tracking_company"),
	fulfilledAt: timestamp("fulfilled_at", { withTimezone: true, mode: 'string' }),
	memo: text(),
	messageToCustomer: text("message_to_customer"),
	class: text(),
	currency: text(),
	exchangeRate: text("exchange_rate"),
	terms: text(),
	salesRep: text("sales_rep"),
	salesChannel: text("sales_channel"),
	customerSegment: text("customer_segment"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	transactionId: bigint("transaction_id", { mode: "number" }),
	quickbooksInternalId: text("quickbooks_internal_id"),
	externalId: text("external_id"),
	createdDate: timestamp("created_date", { mode: 'string' }),
	modifiedDate: timestamp("modified_date", { mode: 'string' }),
	totalLineItemsAmount: numeric("total_line_items_amount"),
	totalTax: doublePrecision("total_tax"),
	totalAmount: numeric("total_amount"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	itemCount: bigint("item_count", { mode: "number" }),
	effectiveTaxRate: numeric("effective_tax_rate"),
});

export const fctOrderLineItemsInAnalyticsMart = analyticsMart.table("fct_order_line_items", {
	lineItemId: varchar("line_item_id"),
	orderKey: text("order_key"),
	orderNumber: varchar("order_number"),
	sourceType: text("source_type"),
	orderDate: date("order_date"),
	customer: varchar(),
	paymentMethod: varchar("payment_method"),
	status: text(),
	dueDate: date("due_date"),
	productService: varchar("product_service"),
	productServiceDescription: varchar("product_service_description"),
	productServiceQuantity: numeric("product_service_quantity"),
	productServiceRate: numeric("product_service_rate"),
	productServiceAmount: numeric("product_service_amount"),
	productServiceClass: varchar("product_service_class"),
	unitOfMeasure: varchar("unit_of_measure"),
	customerSalesTaxCode: varchar("customer_sales_tax_code"),
	isTaxExempt: boolean("is_tax_exempt"),
	productServiceSalesTaxCode: varchar("product_service_sales_tax_code"),
	billingAddress: text("billing_address"),
	billingAddressCity: varchar("billing_address_city"),
	billingAddressState: varchar("billing_address_state"),
	billingAddressPostalCode: varchar("billing_address_postal_code"),
	billingAddressCountry: text("billing_address_country"),
	shippingAddress: text("shipping_address"),
	shippingAddressCity: varchar("shipping_address_city"),
	shippingAddressState: varchar("shipping_address_state"),
	shippingAddressPostalCode: varchar("shipping_address_postal_code"),
	shippingAddressCountry: text("shipping_address_country"),
	primaryCountry: text("primary_country"),
	countryCategory: text("country_category"),
	region: text(),
	shippingMethod: varchar("shipping_method"),
	shipDate: date("ship_date"),
	memo: varchar(),
	messageToCustomer: varchar("message_to_customer"),
	terms: varchar(),
	salesRep: varchar("sales_rep"),
	class: varchar(),
	productServiceServiceDate: varchar("product_service_service_date"),
	inventorySite: varchar("inventory_site"),
	inventoryBin: varchar("inventory_bin"),
	serialNo: varchar("serial_no"),
	lotNo: varchar("lot_no"),
	externalId: varchar("external_id"),
	quickbooksInternalId: varchar("quickbooks_internal_id"),
	currency: varchar(),
	exchangeRate: varchar("exchange_rate"),
	createdDate: timestamp("created_date", { mode: 'string' }),
	modifiedDate: timestamp("modified_date", { mode: 'string' }),
	productFamily: text("product_family"),
	materialType: text("material_type"),
	isKit: boolean("is_kit"),
	itemType: varchar("item_type"),
	itemSubtype: varchar("item_subtype"),
	productSalesDescription: varchar("product_sales_description"),
	standardSalesPrice: numeric("standard_sales_price"),
	standardPurchaseCost: numeric("standard_purchase_cost"),
	marginPercentage: numeric("margin_percentage"),
	marginAmount: numeric("margin_amount"),
	packagingType: text("packaging_type"),
	unitsPerSku: integer("units_per_sku"),
	skuQuantity: numeric("sku_quantity"),
	totalUnitsSold: numeric("total_units_sold"),
	actualUnitPrice: numeric("actual_unit_price"),
	actualMarginAmount: numeric("actual_margin_amount"),
	actualMarginPercentage: numeric("actual_margin_percentage"),
	priceDiscountAmount: numeric("price_discount_amount"),
	priceDiscountPercentage: numeric("price_discount_percentage"),
	primaryContactId: text("primary_contact_id"),
	primaryContactName: text("primary_contact_name"),
	primaryContactEmail: text("primary_contact_email"),
	primaryContactPhone: text("primary_contact_phone"),
	primaryContactRole: text("primary_contact_role"),
});

export const fctTradeShowLeadsInAnalyticsMart = analyticsMart.table("fct_trade_show_leads", {
	leadId: text("lead_id"),
	leadDimKey: text("lead_dim_key"),
	showName: varchar("show_name"),
	showDate: date("show_date"),
	showLocation: text("show_location"),
	showRep: text("show_rep"),
	fullName: text("full_name"),
	firstName: text("first_name"),
	lastName: text("last_name"),
	email: text(),
	phone: text(),
	leadCompanyName: text("lead_company_name"),
	title: text(),
	address1: text("address_1"),
	address2: varchar("address_2"),
	city: text(),
	state: text(),
	postalCode: text("postal_code"),
	country: text(),
	emailDomain: text("email_domain"),
	emailType: text("email_type"),
	companyDomainKey: varchar("company_domain_key", { length: 255 }),
	consolidatedCompanyName: varchar("consolidated_company_name"),
	companyMatchStatus: text("company_match_status"),
	isNewCustomerFromShow: boolean("is_new_customer_from_show"),
	leadEmailIsCustomer: boolean("lead_email_is_customer"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	distinctPurchasersCount: bigint("distinct_purchasers_count", { mode: "number" }),
	companyLifetimeRevenue: doublePrecision("company_lifetime_revenue"),
	companyLifetimeOrders: numeric("company_lifetime_orders"),
	companyFirstOrderDate: date("company_first_order_date"),
	companyLatestOrderDate: date("company_latest_order_date"),
	daysFromShowToFirstOrder: integer("days_from_show_to_first_order"),
	attributed30D: boolean("attributed_30d"),
	attributed90D: boolean("attributed_90d"),
	attributed180D: boolean("attributed_180d"),
	attributed365D: boolean("attributed_365d"),
	attributedAllTime: boolean("attributed_all_time"),
	revenue30D: numeric("revenue_30d"),
	revenue90D: numeric("revenue_90d"),
	revenue180D: numeric("revenue_180d"),
	revenue365D: numeric("revenue_365d"),
	revenueAllTime: numeric("revenue_all_time"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	orders90D: bigint("orders_90d", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	orders365D: bigint("orders_365d", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	ordersAllTime: bigint("orders_all_time", { mode: "number" }),
	hasValidEmail: boolean("has_valid_email"),
	hasCompanyName: boolean("has_company_name"),
	hasPhone: boolean("has_phone"),
	sourceId: text("source_id"),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }),
	updatedAt: timestamp("updated_at", { mode: 'string' }),
	loadDate: timestamp("load_date", { mode: 'string' }),
});

export const fctProductsInAnalyticsMart = analyticsMart.table("fct_products", {
	quickBooksInternalId: varchar("quick_books_internal_id"),
	itemName: varchar("item_name"),
	salesDescription: varchar("sales_description"),
	productFamily: text("product_family"),
	materialType: text("material_type"),
	isKit: boolean("is_kit"),
	itemType: varchar("item_type"),
	itemSubtype: varchar("item_subtype"),
	purchaseDescription: varchar("purchase_description"),
	salesPrice: numeric("sales_price"),
	purchaseCost: numeric("purchase_cost"),
	marginPercentage: numeric("margin_percentage"),
	marginAmount: numeric("margin_amount"),
	manufacturerSPartNumber: varchar("manufacturer_s_part_number"),
	unitOfMeasure: varchar("unit_of_measure"),
	packagingType: text("packaging_type"),
	unitsPerSku: integer("units_per_sku"),
	loadDate: varchar("load_date"),
	snapshotDate: varchar("snapshot_date"),
});

export const martArInvoiceAgingInAnalyticsMart = analyticsMart.table("mart_ar_invoice_aging", {
	orderKey: text("order_key"),
	orderNumber: text("order_number"),
	customer: text(),
	customerSegment: text("customer_segment"),
	orderDate: date("order_date"),
	dueDate: date("due_date"),
	totalAmount: numeric("total_amount"),
	terms: text(),
	daysOutstanding: integer("days_outstanding"),
	daysPastDue: integer("days_past_due"),
	agingBucket: text("aging_bucket"),
	collectionRisk: text("collection_risk"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const fctOrderAttributionInAnalyticsMart = analyticsMart.table("fct_order_attribution", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	orderId: bigint("order_id", { mode: "number" }),
	orderNumber: text("order_number"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	customerId: bigint("customer_id", { mode: "number" }),
	orderDate: date("order_date"),
	orderMonth: date("order_month"),
	acquisitionChannel: text("acquisition_channel"),
	utmSource: text("utm_source"),
	utmMedium: text("utm_medium"),
	utmCampaign: text("utm_campaign"),
	landingSite: text("landing_site"),
	referringSite: varchar("referring_site"),
	revenue: numeric(),
	discountAmount: numeric("discount_amount"),
	shippingAmount: numeric("shipping_amount"),
	taxAmount: numeric("tax_amount"),
	hasDiscount: boolean("has_discount"),
	buyerAcceptsMarketing: boolean("buyer_accepts_marketing"),
	userAgent: varchar("user_agent"),
});

export const fctDsoMetricsInAnalyticsMart = analyticsMart.table("fct_dso_metrics", {
	metricCategory: text("metric_category"),
	period: integer(),
	dsoDays: numeric("dso_days"),
	collectionEfficiencyPct: numeric("collection_efficiency_pct"),
	totalAccountsReceivable: numeric("total_accounts_receivable"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	openInvoiceCount: bigint("open_invoice_count", { mode: "number" }),
	dailyAvgSales: numeric("daily_avg_sales"),
	dsoAssessment: text("dso_assessment"),
	customerSegment: text("customer_segment"),
	segmentAr: numeric("segment_ar"),
	avgDaysOutstanding: numeric("avg_days_outstanding"),
});

export const martArBucketSummaryInAnalyticsMart = analyticsMart.table("mart_ar_bucket_summary", {
	agingBucket: text("aging_bucket"),
	collectionRisk: text("collection_risk"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	invoiceCount: bigint("invoice_count", { mode: "number" }),
	totalArAmount: numeric("total_ar_amount"),
	avgInvoiceAmount: numeric("avg_invoice_amount"),
	avgDaysOutstanding: numeric("avg_days_outstanding"),
	minDaysOutstanding: integer("min_days_outstanding"),
	maxDaysOutstanding: integer("max_days_outstanding"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const martArCustomerSummaryInAnalyticsMart = analyticsMart.table("mart_ar_customer_summary", {
	customer: text(),
	customerSegment: text("customer_segment"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	openInvoiceCount: bigint("open_invoice_count", { mode: "number" }),
	totalArAmount: numeric("total_ar_amount"),
	avgInvoiceAmount: numeric("avg_invoice_amount"),
	avgDaysOutstanding: numeric("avg_days_outstanding"),
	maxDaysOutstanding: integer("max_days_outstanding"),
	overdueArAmount: numeric("overdue_ar_amount"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	overdueInvoiceCount: bigint("overdue_invoice_count", { mode: "number" }),
	paymentPattern: text("payment_pattern"),
	collectionPriority: text("collection_priority"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const fctCompanyProductsInAnalyticsMart = analyticsMart.table("fct_company_products", {
	companyDomainKey: text("company_domain_key"),
	companyName: varchar("company_name"),
	domainType: text("domain_type"),
	businessSizeCategory: text("business_size_category"),
	productService: varchar("product_service"),
	productServiceDescription: varchar("product_service_description"),
	productFamily: text("product_family"),
	materialType: text("material_type"),
	isKit: boolean("is_kit"),
	itemType: text("item_type"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	totalTransactions: bigint("total_transactions", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	purchaseDays: bigint("purchase_days", { mode: "number" }),
	totalQuantityPurchased: numeric("total_quantity_purchased"),
	totalAmountSpent: numeric("total_amount_spent"),
	avgUnitPrice: numeric("avg_unit_price"),
	minUnitPrice: numeric("min_unit_price"),
	maxUnitPrice: numeric("max_unit_price"),
	standardSalesPrice: numeric("standard_sales_price"),
	standardPurchaseCost: numeric("standard_purchase_cost"),
	priceVariancePercentage: numeric("price_variance_percentage"),
	avgMarginPercentage: numeric("avg_margin_percentage"),
	firstPurchaseDate: date("first_purchase_date"),
	latestPurchaseDate: date("latest_purchase_date"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	recentTransactions: bigint("recent_transactions", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	lastYearTransactions: bigint("last_year_transactions", { mode: "number" }),
	daysSinceLastPurchase: integer("days_since_last_purchase"),
	transactionsPerPurchaseDay: numeric("transactions_per_purchase_day"),
	buyerStatus: text("buyer_status"),
	purchaseVolumeCategory: text("purchase_volume_category"),
	purchaseFrequencyCategory: text("purchase_frequency_category"),
	companyTotalRevenue: doublePrecision("company_total_revenue"),
	productRevenuePercentage: numeric("product_revenue_percentage"),
	primarySalesRep: varchar("primary_sales_rep"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const martProductUnitSalesInAnalyticsMart = analyticsMart.table("mart_product_unit_sales", {
	productName: varchar("product_name"),
	packagingType: text("packaging_type"),
	unitsPerSku: integer("units_per_sku"),
	productFamily: text("product_family"),
	materialType: text("material_type"),
	isKit: boolean("is_kit"),
	saleDate: timestamp("sale_date", { withTimezone: true, mode: 'string' }),
	saleWeek: timestamp("sale_week", { withTimezone: true, mode: 'string' }),
	saleMonth: timestamp("sale_month", { withTimezone: true, mode: 'string' }),
	saleQuarter: timestamp("sale_quarter", { withTimezone: true, mode: 'string' }),
	saleYear: timestamp("sale_year", { withTimezone: true, mode: 'string' }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	lineItemCount: bigint("line_item_count", { mode: "number" }),
	totalSkuQuantity: numeric("total_sku_quantity"),
	totalUnitsSold: numeric("total_units_sold"),
	totalRevenue: numeric("total_revenue"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	uniqueCustomers: bigint("unique_customers", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	salesReceiptLines: bigint("sales_receipt_lines", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	invoiceLines: bigint("invoice_lines", { mode: "number" }),
	unitsFromSalesReceipts: numeric("units_from_sales_receipts"),
	unitsFromInvoices: numeric("units_from_invoices"),
	unitsLast30Days: numeric("units_last_30_days"),
	unitsLast90Days: numeric("units_last_90_days"),
	unitsLastYear: numeric("units_last_year"),
	revenuePerUnit: numeric("revenue_per_unit"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const dimAccountsReceivableAgingInAnalyticsMart = analyticsMart.table("dim_accounts_receivable_aging", {
	analysisLevel: text("analysis_level"),
	orderNumber: text("order_number"),
	customer: text(),
	customerSegment: text("customer_segment"),
	orderDate: date("order_date"),
	dueDate: date("due_date"),
	totalAmount: numeric("total_amount"),
	terms: text(),
	daysOutstanding: integer("days_outstanding"),
	daysPastDue: integer("days_past_due"),
	agingBucket: text("aging_bucket"),
	collectionRisk: text("collection_risk"),
	paymentPattern: text("payment_pattern"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	openInvoiceCount: bigint("open_invoice_count", { mode: "number" }),
	totalArAmount: numeric("total_ar_amount"),
	avgDaysOutstanding: numeric("avg_days_outstanding"),
	maxDaysOutstanding: numeric("max_days_outstanding"),
});

export const fctProductPricingHistoryInAnalyticsMart = analyticsMart.table("fct_product_pricing_history", {
	productService: varchar("product_service"),
	orderDate: date("order_date"),
	avgUnitPrice: numeric("avg_unit_price"),
	totalUnitsSold: numeric("total_units_sold"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	transactionCount: bigint("transaction_count", { mode: "number" }),
	isActualProduct: boolean("is_actual_product"),
	priceCluster: numeric("price_cluster"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	clusterFrequency30D: bigint("cluster_frequency_30d", { mode: "number" }),
	clusterVolume30D: numeric("cluster_volume_30d"),
	volumeCategory: text("volume_category"),
	stableRetailCandidate: numeric("stable_retail_candidate"),
	dominantPriceCandidate: numeric("dominant_price_candidate"),
	inferredRetailPrice: numeric("inferred_retail_price"),
	authoritativePrice: numeric("authoritative_price"),
	priceEffectiveDate: date("price_effective_date"),
	retailPriceAtDate: numeric("retail_price_at_date"),
	retailPriceSource: text("retail_price_source"),
	prevAvgPrice: numeric("prev_avg_price"),
	prevSaleDate: date("prev_sale_date"),
	prevRetailPrice: numeric("prev_retail_price"),
	priceTrend: text("price_trend"),
	priceChangeAmount: numeric("price_change_amount"),
	priceChangePercentage: numeric("price_change_percentage"),
	daysSinceLastSale: integer("days_since_last_sale"),
	productFamily: text("product_family"),
	materialType: text("material_type"),
	isKit: boolean("is_kit"),
	itemType: varchar("item_type"),
	itemSubtype: varchar("item_subtype"),
	currentListPrice: numeric("current_list_price"),
	currentPurchaseCost: numeric("current_purchase_cost"),
	discountFromRetailPct: numeric("discount_from_retail_pct"),
	discountFromRetailAmount: numeric("discount_from_retail_amount"),
	retailPriceChangeType: text("retail_price_change_type"),
	retailPriceChangeAmount: numeric("retail_price_change_amount"),
	retailPriceChangePct: numeric("retail_price_change_pct"),
	discountFromCurrentListPct: numeric("discount_from_current_list_pct"),
	discountFromCurrentListAmount: numeric("discount_from_current_list_amount"),
});

export const fctCompanyOrdersInAnalyticsMart = analyticsMart.table("fct_company_orders", {
	companyDomainKey: text("company_domain_key"),
	companyName: varchar("company_name"),
	domainType: text("domain_type"),
	businessSizeCategory: text("business_size_category"),
	orderNumber: varchar("order_number"),
	orderType: text("order_type"),
	orderDate: date("order_date"),
	customerName: varchar("customer_name"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	lineItemCount: bigint("line_item_count", { mode: "number" }),
	calculatedOrderTotal: numeric("calculated_order_total"),
	reportedOrderTotal: numeric("reported_order_total"),
	orderTax: numeric("order_tax"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	uniqueProducts: bigint("unique_products", { mode: "number" }),
	productFamilies: text("product_families"),
	materialTypes: text("material_types"),
	kitQuantity: numeric("kit_quantity"),
	kitAmount: numeric("kit_amount"),
	avgMarginPercentage: numeric("avg_margin_percentage"),
	salesRep: varchar("sales_rep"),
	paymentMethod: varchar("payment_method"),
	terms: varchar(),
	orderYear: numeric("order_year"),
	orderQuarter: numeric("order_quarter"),
	recencyCategory: text("recency_category"),
	orderSizeCategory: text("order_size_category"),
	productDiversity: text("product_diversity"),
	daysSinceOrder: integer("days_since_order"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const martProductMarginAnalyticsInAnalyticsMart = analyticsMart.table("mart_product_margin_analytics", {
	timePeriod: text("time_period"),
	sku: varchar(),
	periodDate: timestamp("period_date", { withTimezone: true, mode: 'string' }),
	orderDate: date("order_date"),
	orderMonth: timestamp("order_month", { withTimezone: true, mode: 'string' }),
	orderYear: timestamp("order_year", { withTimezone: true, mode: 'string' }),
	productFamily: text("product_family"),
	materialType: text("material_type"),
	isKit: boolean("is_kit"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	transactionCount: bigint("transaction_count", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	uniqueCustomers: bigint("unique_customers", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	uniqueOrders: bigint("unique_orders", { mode: "number" }),
	totalQuantitySold: numeric("total_quantity_sold"),
	totalUnitsSold: numeric("total_units_sold"),
	totalRevenue: numeric("total_revenue"),
	avgUnitPrice: numeric("avg_unit_price"),
	avgStandardPrice: numeric("avg_standard_price"),
	avgPurchaseCost: numeric("avg_purchase_cost"),
	avgStandardMarginPercentage: numeric("avg_standard_margin_percentage"),
	totalMarginAmount: numeric("total_margin_amount"),
	avgUnitMarginAmount: numeric("avg_unit_margin_amount"),
	avgMarginPercentage: numeric("avg_margin_percentage"),
	volumeWeightedMarginPercentage: numeric("volume_weighted_margin_percentage"),
	totalDiscountAmount: numeric("total_discount_amount"),
	volumeWeightedDiscountPercentage: numeric("volume_weighted_discount_percentage"),
});

export const martMarketingPerformanceInAnalyticsMart = analyticsMart.table("mart_marketing_performance", {
	orderMonth: date("order_month"),
	acquisitionChannel: text("acquisition_channel"),
	utmSource: text("utm_source"),
	utmMedium: text("utm_medium"),
	utmCampaign: text("utm_campaign"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	orderCount: bigint("order_count", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	customerCount: bigint("customer_count", { mode: "number" }),
	totalRevenue: numeric("total_revenue"),
	totalDiscounts: numeric("total_discounts"),
	avgOrderValue: numeric("avg_order_value"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	discountedOrders: bigint("discounted_orders", { mode: "number" }),
	discountRate: numeric("discount_rate"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	marketingOptIns: bigint("marketing_opt_ins", { mode: "number" }),
	optInRate: numeric("opt_in_rate"),
});

export const martProductCompanyPeriodSpendingInAnalyticsMart = analyticsMart.table("mart_product_company_period_spending", {
	productService: varchar("product_service"),
	companyDomainKey: text("company_domain_key"),
	periodType: text("period_type"),
	totalAmountSpent: numeric("total_amount_spent"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	totalTransactions: bigint("total_transactions", { mode: "number" }),
	totalQuantityPurchased: numeric("total_quantity_purchased"),
	avgUnitPrice: numeric("avg_unit_price"),
	firstPurchaseDate: date("first_purchase_date"),
	lastPurchaseDate: date("last_purchase_date"),
	latestCustomer: text("latest_customer"),
	latestSourceType: text("latest_source_type"),
	companyName: varchar("company_name"),
	domainType: text("domain_type"),
	businessSizeCategory: text("business_size_category"),
	companyTotalRevenue: doublePrecision("company_total_revenue"),
	productFamily: text("product_family"),
	materialType: text("material_type"),
	isKit: boolean("is_kit"),
	itemType: text("item_type"),
	standardSalesPrice: numeric("standard_sales_price"),
	standardPurchaseCost: numeric("standard_purchase_cost"),
	standardMarginPercentage: numeric("standard_margin_percentage"),
	lifetimeBuyerStatus: text("lifetime_buyer_status"),
	lifetimeVolumeCategory: text("lifetime_volume_category"),
	lifetimeFrequencyCategory: text("lifetime_frequency_category"),
	lifetimeTotalSpent: numeric("lifetime_total_spent"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	lifetimeTotalTransactions: bigint("lifetime_total_transactions", { mode: "number" }),
	periodBuyerStatus: text("period_buyer_status"),
	periodSpendingCategory: text("period_spending_category"),
	priceVariancePercentage: numeric("price_variance_percentage"),
	periodShareOfLifetimeSpending: numeric("period_share_of_lifetime_spending"),
	daysSinceLastPurchase: integer("days_since_last_purchase"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const bridgeCustomerCompanyInAnalyticsMart = analyticsMart.table("bridge_customer_company", {
	customerId: varchar("customer_id"),
	companyDomainKey: text("company_domain_key"),
	customerName: varchar("customer_name"),
	customerCompanyName: varchar("customer_company_name"),
	standardizedCustomerName: text("standardized_customer_name"),
	customerNameNormalizationType: text("customer_name_normalization_type"),
	mainEmail: varchar("main_email"),
	ccEmail: varchar("cc_email"),
	mainPhone: varchar("main_phone"),
	billingAddressLine1: varchar("billing_address_line_1"),
	billingAddressCity: varchar("billing_address_city"),
	billingAddressState: varchar("billing_address_state"),
	billingAddressPostalCode: varchar("billing_address_postal_code"),
	salesRep: varchar("sales_rep"),
	terms: varchar(),
	priceLevel: varchar("price_level"),
	currentBalance: numeric("current_balance", { precision: 38, scale:  9 }),
	customerStatus: varchar("customer_status"),
	customerCreatedDate: timestamp("customer_created_date", { mode: 'string' }),
	customerModifiedDate: timestamp("customer_modified_date", { mode: 'string' }),
	domainType: text("domain_type"),
	customerTotalRevenue: doublePrecision("customer_total_revenue"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	customerTotalOrders: bigint("customer_total_orders", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	customerTotalLineItems: bigint("customer_total_line_items", { mode: "number" }),
	customerFirstOrderDate: date("customer_first_order_date"),
	customerLatestOrderDate: date("customer_latest_order_date"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	customerOrderDays: bigint("customer_order_days", { mode: "number" }),
	customerValueTier: text("customer_value_tier"),
	customerActivityStatus: text("customer_activity_status"),
	ordersPerDay: numeric("orders_per_day"),
	isIndividualCustomer: boolean("is_individual_customer"),
	isMissingEmail: boolean("is_missing_email"),
	hasRevenue: boolean("has_revenue"),
	isActiveCustomer: boolean("is_active_customer"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const fctTradeShowPerformanceInAnalyticsMart = analyticsMart.table("fct_trade_show_performance", {
	showName: varchar("show_name"),
	showDate: date("show_date"),
	showLocation: text("show_location"),
	showRep: text("show_rep"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	totalLeadsCollected: bigint("total_leads_collected", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	uniqueEmailsCollected: bigint("unique_emails_collected", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	validEmails: bigint("valid_emails", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	companiesMatched: bigint("companies_matched", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	leadsMatchedToCompanies: bigint("leads_matched_to_companies", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	leadsUnmatched: bigint("leads_unmatched", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	leadsIndividualEmails: bigint("leads_individual_emails", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	leadsWhoAreDirectCustomers: bigint("leads_who_are_direct_customers", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	leadsAttributedViaCompanyColleagues: bigint("leads_attributed_via_company_colleagues", { mode: "number" }),
	totalDistinctPurchasers: numeric("total_distinct_purchasers"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	newCustomersAcquired: bigint("new_customers_acquired", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	conversions30D: bigint("conversions_30d", { mode: "number" }),
	totalRevenue30D: numeric("total_revenue_30d"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	conversions90D: bigint("conversions_90d", { mode: "number" }),
	totalRevenue90D: numeric("total_revenue_90d"),
	totalOrders90D: numeric("total_orders_90d"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	conversions180D: bigint("conversions_180d", { mode: "number" }),
	totalRevenue180D: numeric("total_revenue_180d"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	conversions365D: bigint("conversions_365d", { mode: "number" }),
	totalRevenue365D: numeric("total_revenue_365d"),
	totalOrders365D: numeric("total_orders_365d"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	conversionsAllTime: bigint("conversions_all_time", { mode: "number" }),
	totalRevenueAllTime: numeric("total_revenue_all_time"),
	totalOrdersAllTime: numeric("total_orders_all_time"),
	avgDaysToConversion90D: numeric("avg_days_to_conversion_90d"),
	avgDaysToConversion365D: numeric("avg_days_to_conversion_365d"),
	avgDaysToConversionAllTime: numeric("avg_days_to_conversion_all_time"),
	matchRatePct: numeric("match_rate_pct"),
	conversionRate90DPct: numeric("conversion_rate_90d_pct"),
	conversionRate365DPct: numeric("conversion_rate_365d_pct"),
	conversionRateAllTimePct: numeric("conversion_rate_all_time_pct"),
	revenuePerLead90D: numeric("revenue_per_lead_90d"),
	revenuePerLead365D: numeric("revenue_per_lead_365d"),
	revenuePerLeadAllTime: numeric("revenue_per_lead_all_time"),
	showPerformance90D: text("show_performance_90d"),
	showPerformance365D: text("show_performance_365d"),
	showPerformanceAllTime: text("show_performance_all_time"),
});

export const dimCompanyHealthInAnalyticsMart = analyticsMart.table("dim_company_health", {
	companyDomainKey: text("company_domain_key"),
	companyName: varchar("company_name"),
	domainType: text("domain_type"),
	businessSizeCategory: text("business_size_category"),
	revenueCategory: text("revenue_category"),
	healthScore: numeric("health_score"),
	customerArchetype: text("customer_archetype"),
	activityStatus: text("activity_status"),
	engagementLevel: text("engagement_level"),
	growthTrendDirection: text("growth_trend_direction"),
	combinedGrowthTrend: text("combined_growth_trend"),
	orderFrequencyCategory: text("order_frequency_category"),
	daysSinceLastOrder: integer("days_since_last_order"),
	lastOrderDate: date("last_order_date"),
	firstOrderDate: date("first_order_date"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	totalOrders: bigint("total_orders", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	activeYears: bigint("active_years", { mode: "number" }),
	ordersPerYear: numeric("orders_per_year"),
	totalRevenue: numeric("total_revenue"),
	avgOrderValue: numeric("avg_order_value"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	ordersLast90Days: bigint("orders_last_90_days", { mode: "number" }),
	revenueLast90Days: numeric("revenue_last_90_days"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	ordersLastYear: bigint("orders_last_year", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	ordersPriorYear: bigint("orders_prior_year", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	productDiversityScore: bigint("product_diversity_score", { mode: "number" }),
	revenuePercentile: doublePrecision("revenue_percentile"),
	healthCategory: text("health_category"),
	atRiskFlag: boolean("at_risk_flag"),
	growthOpportunityFlag: boolean("growth_opportunity_flag"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const fctCompanyOrdersTimeSeriesInAnalyticsMart = analyticsMart.table("fct_company_orders_time_series", {
	companyDomainKey: text("company_domain_key"),
	companyName: varchar("company_name"),
	domainType: text("domain_type"),
	businessSizeCategory: text("business_size_category"),
	revenueCategory: text("revenue_category"),
	orderYear: numeric("order_year"),
	orderQuarter: numeric("order_quarter"),
	periodKey: text("period_key"),
	periodStartDate: date("period_start_date"),
	periodEndDate: date("period_end_date"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	orderCount: bigint("order_count", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	uniqueCustomers: bigint("unique_customers", { mode: "number" }),
	totalRevenue: numeric("total_revenue"),
	avgOrderValue: numeric("avg_order_value"),
	totalUniqueProducts: numeric("total_unique_products"),
	avgProductsPerOrder: numeric("avg_products_per_order"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	largeOrders: bigint("large_orders", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	mediumOrders: bigint("medium_orders", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	smallOrders: bigint("small_orders", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	microOrders: bigint("micro_orders", { mode: "number" }),
	avgMarginPercentage: numeric("avg_margin_percentage"),
	qoqOrderGrowthPct: numeric("qoq_order_growth_pct"),
	qoqRevenueGrowthPct: numeric("qoq_revenue_growth_pct"),
	yoyOrderGrowthPct: numeric("yoy_order_growth_pct"),
	yoyRevenueGrowthPct: numeric("yoy_revenue_growth_pct"),
	yoyGrowthTrend: text("yoy_growth_trend"),
	yoyRevenueTrend: text("yoy_revenue_trend"),
	quarterlyRevenueTier: text("quarterly_revenue_tier"),
	quarterlyActivityLevel: text("quarterly_activity_level"),
	quarterLabel: text("quarter_label"),
	isCurrentQuarter: boolean("is_current_quarter"),
	exceptionalGrowthFlag: boolean("exceptional_growth_flag"),
	concerningDeclineFlag: boolean("concerning_decline_flag"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});

export const fctCustomerMarketingInAnalyticsMart = analyticsMart.table("fct_customer_marketing", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	customerId: bigint("customer_id", { mode: "number" }),
	email: varchar(),
	fullName: text("full_name"),
	companyName: varchar("company_name"),
	isEmailSubscriber: boolean("is_email_subscriber"),
	isSmsSubscriber: boolean("is_sms_subscriber"),
	emailConsentDate: timestamp("email_consent_date", { withTimezone: true, mode: 'string' }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	shopifyOrderCount: bigint("shopify_order_count", { mode: "number" }),
	shopifyLifetimeValue: numeric("shopify_lifetime_value"),
	avgOrderValue: numeric("avg_order_value"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	discountedOrderCount: bigint("discounted_order_count", { mode: "number" }),
	discountUsageRate: numeric("discount_usage_rate"),
	firstOrderDate: timestamp("first_order_date", { withTimezone: true, mode: 'string' }),
	lastOrderDate: timestamp("last_order_date", { withTimezone: true, mode: 'string' }),
	daysSinceLastOrder: integer("days_since_last_order"),
	customerSegment: text("customer_segment"),
	customerStatus: text("customer_status"),
});

export const martCompanyPeriodMetricsInAnalyticsMart = analyticsMart.table("mart_company_period_metrics", {
	companyDomainKey: text("company_domain_key"),
	periodType: text("period_type"),
	totalRevenue: numeric("total_revenue"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	totalOrders: bigint("total_orders", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	customerCount: bigint("customer_count", { mode: "number" }),
	firstOrderDate: date("first_order_date"),
	latestOrderDate: date("latest_order_date"),
	companyName: varchar("company_name"),
	domainType: text("domain_type"),
	businessSizeCategory: text("business_size_category"),
	lifetimeTotalRevenue: doublePrecision("lifetime_total_revenue"),
	lifetimeTotalOrders: numeric("lifetime_total_orders"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	lifetimeCustomerCount: bigint("lifetime_customer_count", { mode: "number" }),
	lifetimeRevenueCategory: text("lifetime_revenue_category"),
	hasRevenue: boolean("has_revenue"),
	isMultiLocation: boolean("is_multi_location"),
	isCorporate: boolean("is_corporate"),
	periodActivityStatus: text("period_activity_status"),
	periodRevenueCategory: text("period_revenue_category"),
	periodShareOfLifetimeRevenue: numeric("period_share_of_lifetime_revenue"),
	daysSinceLatestOrder: integer("days_since_latest_order"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
});
export const baseFctOrdersCurrentInAnalyticsMart = analyticsMart.view("base_fct_orders_current", {	orderKey: text("order_key"),
	orderNumber: text("order_number"),
	sourceType: text("source_type"),
	orderDate: date("order_date"),
	customer: text(),
	paymentMethod: text("payment_method"),
	status: text(),
	dueDate: date("due_date"),
	primaryContactId: text("primary_contact_id"),
	primaryContactName: text("primary_contact_name"),
	primaryContactEmail: text("primary_contact_email"),
	primaryContactPhone: text("primary_contact_phone"),
	primaryContactRole: text("primary_contact_role"),
	isTaxExempt: boolean("is_tax_exempt"),
	isPaid: boolean("is_paid"),
	isBackdated: boolean("is_backdated"),
	billingAddress: text("billing_address"),
	billingAddressCity: text("billing_address_city"),
	billingAddressState: text("billing_address_state"),
	billingAddressPostalCode: text("billing_address_postal_code"),
	billingAddressCountry: text("billing_address_country"),
	shippingAddress: text("shipping_address"),
	shippingAddressCity: text("shipping_address_city"),
	shippingAddressState: text("shipping_address_state"),
	shippingAddressPostalCode: text("shipping_address_postal_code"),
	shippingAddressCountry: text("shipping_address_country"),
	primaryCountry: text("primary_country"),
	countryCategory: text("country_category"),
	region: text(),
	shippingMethod: text("shipping_method"),
	shipDate: date("ship_date"),
	salesChannelSource: text("sales_channel_source"),
	acquisitionChannel: text("acquisition_channel"),
	utmSource: text("utm_source"),
	utmMedium: text("utm_medium"),
	utmCampaign: text("utm_campaign"),
	landingSite: text("landing_site"),
	referringSite: varchar("referring_site"),
	trackingNumber: text("tracking_number"),
	trackingCompany: text("tracking_company"),
	fulfilledAt: timestamp("fulfilled_at", { withTimezone: true, mode: 'string' }),
	memo: text(),
	messageToCustomer: text("message_to_customer"),
	class: text(),
	currency: text(),
	exchangeRate: text("exchange_rate"),
	terms: text(),
	salesRep: text("sales_rep"),
	salesChannel: text("sales_channel"),
	customerSegment: text("customer_segment"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	transactionId: bigint("transaction_id", { mode: "number" }),
	quickbooksInternalId: text("quickbooks_internal_id"),
	externalId: text("external_id"),
	createdDate: timestamp("created_date", { mode: 'string' }),
	modifiedDate: timestamp("modified_date", { mode: 'string' }),
	totalLineItemsAmount: numeric("total_line_items_amount"),
	totalTax: doublePrecision("total_tax"),
	totalAmount: numeric("total_amount"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	itemCount: bigint("item_count", { mode: "number" }),
	effectiveTaxRate: numeric("effective_tax_rate"),
}).as(sql`SELECT order_key, order_number, source_type, order_date, customer, payment_method, status, due_date, primary_contact_id, primary_contact_name, primary_contact_email, primary_contact_phone, primary_contact_role, is_tax_exempt, is_paid, is_backdated, billing_address, billing_address_city, billing_address_state, billing_address_postal_code, billing_address_country, shipping_address, shipping_address_city, shipping_address_state, shipping_address_postal_code, shipping_address_country, primary_country, country_category, region, shipping_method, ship_date, sales_channel_source, acquisition_channel, utm_source, utm_medium, utm_campaign, landing_site, referring_site, tracking_number, tracking_company, fulfilled_at, memo, message_to_customer, class, currency, exchange_rate, terms, sales_rep, sales_channel, customer_segment, transaction_id, quickbooks_internal_id, external_id, created_date, modified_date, total_line_items_amount, total_tax, total_amount, item_count, effective_tax_rate FROM analytics_mart.fct_orders WHERE order_date <= CURRENT_DATE`);

export const baseFctOrderLineItemsCurrentInAnalyticsMart = analyticsMart.view("base_fct_order_line_items_current", {	lineItemId: varchar("line_item_id"),
	orderKey: text("order_key"),
	orderNumber: varchar("order_number"),
	sourceType: text("source_type"),
	orderDate: date("order_date"),
	customer: varchar(),
	paymentMethod: varchar("payment_method"),
	status: text(),
	dueDate: date("due_date"),
	productService: varchar("product_service"),
	productServiceDescription: varchar("product_service_description"),
	productServiceQuantity: numeric("product_service_quantity"),
	productServiceRate: numeric("product_service_rate"),
	productServiceAmount: numeric("product_service_amount"),
	productServiceClass: varchar("product_service_class"),
	unitOfMeasure: varchar("unit_of_measure"),
	customerSalesTaxCode: varchar("customer_sales_tax_code"),
	isTaxExempt: boolean("is_tax_exempt"),
	productServiceSalesTaxCode: varchar("product_service_sales_tax_code"),
	billingAddress: text("billing_address"),
	billingAddressCity: varchar("billing_address_city"),
	billingAddressState: varchar("billing_address_state"),
	billingAddressPostalCode: varchar("billing_address_postal_code"),
	billingAddressCountry: text("billing_address_country"),
	shippingAddress: text("shipping_address"),
	shippingAddressCity: varchar("shipping_address_city"),
	shippingAddressState: varchar("shipping_address_state"),
	shippingAddressPostalCode: varchar("shipping_address_postal_code"),
	shippingAddressCountry: text("shipping_address_country"),
	primaryCountry: text("primary_country"),
	countryCategory: text("country_category"),
	region: text(),
	shippingMethod: varchar("shipping_method"),
	shipDate: date("ship_date"),
	memo: varchar(),
	messageToCustomer: varchar("message_to_customer"),
	terms: varchar(),
	salesRep: varchar("sales_rep"),
	class: varchar(),
	productServiceServiceDate: varchar("product_service_service_date"),
	inventorySite: varchar("inventory_site"),
	inventoryBin: varchar("inventory_bin"),
	serialNo: varchar("serial_no"),
	lotNo: varchar("lot_no"),
	externalId: varchar("external_id"),
	quickbooksInternalId: varchar("quickbooks_internal_id"),
	currency: varchar(),
	exchangeRate: varchar("exchange_rate"),
	createdDate: timestamp("created_date", { mode: 'string' }),
	modifiedDate: timestamp("modified_date", { mode: 'string' }),
	productFamily: text("product_family"),
	materialType: text("material_type"),
	isKit: boolean("is_kit"),
	itemType: varchar("item_type"),
	itemSubtype: varchar("item_subtype"),
	productSalesDescription: varchar("product_sales_description"),
	standardSalesPrice: numeric("standard_sales_price"),
	standardPurchaseCost: numeric("standard_purchase_cost"),
	marginPercentage: numeric("margin_percentage"),
	marginAmount: numeric("margin_amount"),
	packagingType: text("packaging_type"),
	unitsPerSku: integer("units_per_sku"),
	skuQuantity: numeric("sku_quantity"),
	totalUnitsSold: numeric("total_units_sold"),
	actualUnitPrice: numeric("actual_unit_price"),
	actualMarginAmount: numeric("actual_margin_amount"),
	actualMarginPercentage: numeric("actual_margin_percentage"),
	priceDiscountAmount: numeric("price_discount_amount"),
	priceDiscountPercentage: numeric("price_discount_percentage"),
	primaryContactId: text("primary_contact_id"),
	primaryContactName: text("primary_contact_name"),
	primaryContactEmail: text("primary_contact_email"),
	primaryContactPhone: text("primary_contact_phone"),
	primaryContactRole: text("primary_contact_role"),
}).as(sql`SELECT li.line_item_id, li.order_key, li.order_number, li.source_type, li.order_date, li.customer, li.payment_method, li.status, li.due_date, li.product_service, li.product_service_description, li.product_service_quantity, li.product_service_rate, li.product_service_amount, li.product_service_class, li.unit_of_measure, li.customer_sales_tax_code, li.is_tax_exempt, li.product_service_sales_tax_code, li.billing_address, li.billing_address_city, li.billing_address_state, li.billing_address_postal_code, li.billing_address_country, li.shipping_address, li.shipping_address_city, li.shipping_address_state, li.shipping_address_postal_code, li.shipping_address_country, li.primary_country, li.country_category, li.region, li.shipping_method, li.ship_date, li.memo, li.message_to_customer, li.terms, li.sales_rep, li.class, li.product_service_service_date, li.inventory_site, li.inventory_bin, li.serial_no, li.lot_no, li.external_id, li.quickbooks_internal_id, li.currency, li.exchange_rate, li.created_date, li.modified_date, li.product_family, li.material_type, li.is_kit, li.item_type, li.item_subtype, li.product_sales_description, li.standard_sales_price, li.standard_purchase_cost, li.margin_percentage, li.margin_amount, li.packaging_type, li.units_per_sku, li.sku_quantity, li.total_units_sold, li.actual_unit_price, li.actual_margin_amount, li.actual_margin_percentage, li.price_discount_amount, li.price_discount_percentage, li.primary_contact_id, li.primary_contact_name, li.primary_contact_email, li.primary_contact_phone, li.primary_contact_role FROM analytics_mart.fct_order_line_items li JOIN analytics_mart.base_fct_orders_current o ON li.order_key = o.order_key`);
