# Name of your application. Used to uniquely configure containers.
service: aacd

# Name of the container image.
image: teich/aacd

# Deploy to these servers.
servers:
  - aac

proxy:
  ssl: false
  app_port: 3000
  healthcheck:
    path: /
    interval: 5

# Credentials for your image host.
registry:
  username: teich
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  secrets:
    - DATABASE_URL
    - COMPANIES_API_TOKEN
  remote: ssh://root@aac

env:
  secret:
    - DATABASE_URL

asset_path: /app/.next
