# Name of your application. Used to uniquely configure containers.
service: aacd

# Name of the container image.
image: asphaltanchors/aacd

# Deploy to these servers.
servers:
  - aac

proxy:
  ssl: false
  app_port: 3000
  healthcheck:
    path: /
    interval: 5

# Credentials for your image host.
registry:
  server: ghcr.io
  username: teich
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  secrets:
    - DATABASE_URL
  remote: ssh://root@aac

env:
  secret:
    - DATABASE_URL
    - COMPANIES_API_TOKEN


volumes:
  - /mnt/dropbox/db/AAC/Oren/CSV:/CSV

asset_path: /app/.next
